all: prg

prg: tmp_stat.o temp_sys.o temp_api.o
	gcc -o .\bin\tmp_stat tmp_stat.o temp_sys.o temp_api.o -ggdb3

tmp_stat.o: .\src\tmp_stat.c
	gcc -c -o tmp_stat.o .\src\tmp_stat.c -I .\include\ -ggdb3

temp_sys.o: .\src\temp_sys.c
	gcc -c -o temp_sys.o .\src\temp_sys.c -I .\include\ -ggdb3

temp_api.o: .\src\temp_api.c
	gcc -c -o temp_api.o .\src\temp_api.c -I .\include\ -ggdb3

clean: 
	del .\bin\*.exe 
	del *.o   